monitor.alsa.rules = [
  { matches = [ { node.name = "alsa_output.pci-0000_73_00.1.hdmi-stereo" } ]
    actions = { update-props = { priority.session = 1500 } } }
  { matches = [ { node.name = "alsa_output.pci-0000_73_00.6.analog-stereo" } ]
    actions = { update-props = { priority.session = 1000 } } }
  { matches = [ { node.name = "alsa_output.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo" } ]
    actions = { update-props = { priority.session = 100 } } }
  { matches = [ { node.name = "alsa_input.usb-Focusrite_Scarlett_2i2_USB-00.analog-stereo" } ]
    actions = { update-props = { priority.session = 2500 } } }
  { matches = [ { node.name = "alsa_input.pci-0000_73_00.6.analog-stereo" } ]
    actions = { update-props = { priority.session = 2000 } } }
  { matches = [ { node.name = "alsa_input.usb-046d_Logitech_StreamCam_1519A455-02.analog-stereo" } ]
    actions = { update-props = { priority.session = 500 } } }
]

monitor.bluez.rules = [
  { matches = [ { node.name = "bluez_output.34_82_C5_D3_ED_3D.1" } ]
    actions = { update-props = { priority.session = 2000 } } }
  { matches = [ { node.name = "bluez_output.BC_87_FA_33_D1_45.1" } ]
    actions = { update-props = { priority.session = 2000 } } }
]
